---
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-json
      - id: mixed-line-ending
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: .*\.html

  - repo: local
    hooks:
      - id: isort-poetry
        name: isort-poetry
        entry: poetry run isort
        language: system
        types: [python]

      - id: black-poetry
        name: black-poetry
        entry: poetry run black
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: poetry run pytest tests
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        args:
          - --show-traceback
          - --ignore-missing-imports
          - --check-untyped-defs

      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          - --rcfile=.pylintrc
