[tool.poetry]
name = "xoto3"
version = "2.2.0"
authors = ["Peter Gaultney <pgaultney@xoi.io>"]
description = "High level utilities for a subset of boto3 operations common for AWS serverless development in Python."
readme = "README.md"
packages = [{ include = "xoto3" }]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
boto3 = ">=1.28.27"


[tool.poetry.group.dev.dependencies]
black = "26.3.1"  # must match .pre-commit-config.yaml rev
isort = "8.0.1"  # must match .pre-commit-config.yaml rev
mypy = "^1.19.1"
poetry = "^2.3.2"
pre-commit = "^4.5.1"
pylint = "^4.0.5"
pytest = "^9.0.2"
pytest-cov = "^7.1.0"
pytest-xdist = "^3.8.0"
awslambdaric = ">=2.0.0"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py312']
